server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uywojh/springcloud/
          search-paths: config-repo
          username: 664507439@qq.com
          password: wu15180180820